### ISSUE TITLE
User connections is broken

### ISSUE THREAD

**Issue by dandgelb** [dandgelb/messaging-service#2]
FIXME in: https://github.com/dandgelb/messaging-service/commit/62f0f404dccc117e686b8da82455855357a7abf8

**Comment by dandgelb** [comment]
For following difference in source:
```diff
diff --git a/src/main/java/com/example/messagingservice/MessagingServiceApplication.java b/src/main/java/com/example/messagingservice/MessagingServiceApplication.java
index 95073fb..fc685bb 100644
--- a/src/main/java/com/example/messagingservice/MessagingServiceApplication.java
+++ b/src/main/java/com/example/messagingservice/MessagingServiceApplication.java
@@ -44,8 +44,8 @@ class SampleUserDataCLR implements CommandLineRunner {
         userRepository.save(new User(new Long(1), set));
 
         HashSet s2 = new HashSet<>();
-        s2.add(new User(new Long(2)));
-        userRepository.save(new User(new Long(3), s2));
+        s2.add(new User(new Long(1)));
+        userRepository.save(new User(new Long(2), s2));
 
         //print
         userRepository.findAll().forEach(System.out::println);
```
Logs:
```console
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-06-01 18:49:29.490 ERROR 14351 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.StackOverflowError: null
	at java.util.HashSet.iterator(HashSet.java:172) ~[na:1.8.0_73]
	at java.util.AbstractSet.hashCode(AbstractSet.java:122) ~[na:1.8.0_73]
	at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:431) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at com.example.messagingservice.User.hashCode(MessagingServiceApplication.java:61) ~[classes/:na]
	at java.util.AbstractSet.hashCode(AbstractSet.java:126) ~[na:1.8.0_73]
	at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:431) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at com.example.messagingservice.User.hashCode(MessagingServiceApplication.java:61) ~[classes/:na]
	at java.util.AbstractSet.hashCode(AbstractSet.java:126) ~[na:1.8.0_73]
	at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:431) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at com.example.messagingservice.User.hashCode(MessagingServiceApplication.java:61) ~[classes/:na]
	at java.util.AbstractSet.hashCode(AbstractSet.java:126) ~[na:1.8.0_73]
```

**Comment by dandgelb** [comment]
Fixed `connection` model in https://github.com/dandgelb/messaging-service/commit/b11bb3f10d4f5525faf17398a29ce858dc6c16cd

Repository to access `connection` is pending.

**Comment by dandgelb** [comment]
GET connection list using RestController `/users/{id}/connections` - https://github.com/dandgelb/messaging-service/commit/d04d834bc874b4142cf75c880bc0d68ea3479ef0
